apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres16-userdev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 60Gi  
  storageClassName: managed-csi
