apiVersion: apps/v1
kind: Deployment
metadata:
  name: appmonitor-dev
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      app: appmonitor-dev
  template:
    metadata:
      labels:
        app: appmonitor-dev
      namespace: jason	
    spec:
      containers:
        - env:
            - name: DEBUG
              value: 'True'
            - name: ENABLE_WEB
              value: 'False'
            - name: ENABLE_CRON
              value: 'False'
          name: appmonitor-dev
          image: dbcawa/docker_app_dev:appmonitor_dev_2025.05.04.15.0438
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: tcp8080
              protocol: TCP
          stdin: true          
          tty: true     
          volumeMounts:
            - mountPath: /data/
              name: appmonitor-dev
              subPath: data                  
            - mountPath: /home/container/
              name: appmonitor-dev
              subPath: container   
          workingDir: /data/data/projects/appmonitor/
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 2Gi          
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL          
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 200000           
      volumes:
        - name:  appmonitor-dev
          persistentVolumeClaim:
            claimName: appmonitor-dev
            
