apiVersion: v1
kind: Service
metadata:
  name: ledgergw-userdev
spec:
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-{{namespace}}-ledgergw-userdev
  ports:
    - protocol: TCP
      port: 7001
      targetPort: 8080
    - protocol: TCP
      port: 9021
      targetPort: 9021


      
